version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_referral_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_referral
    outputs:
      highly_sensitive:
        cohort: output/input_referral.csv

  generate_symptom_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_symptom
    outputs:
      highly_sensitive:
        cohort: output/input_symptom.csv

  describe:
    run: python:latest python analysis/report.py
    needs: [generate_referral_cohort, generate_symptom_cohort]
    outputs:
      moderately_sensitive:
        all_figure: output/colorectal_cancer.jpg
