version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_lowerGI_wholecohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_lowerGI_wholecohort --index-date-range "2018-03-01 to 2023-08-01 by month" --skip-existing --output-dir=output --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv.gz

  generate_demovar_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_demovar --output-dir=output --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_demovar.csv.gz

  join_lowerGIwhole:
    run: >
      cohort-joiner:v.0.0.30
        --lhs output/input_*.csv.gz
        --rhs output/input_demovar.csv.gz
        --output-dir output/joined
        --output-format=csv.gz
    needs: [generate_lowerGI_wholecohort, generate_demovar_cohort]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_joined_*.csv.gz

  generate_measures_lowerGIwhole:
    run: cohortextractor:latest generate_measures --study-definition study_definition_lowerGI_wholecohort --skip-existing --output-dir=output/joined
    needs: [join_lowerGIwhole]
    outputs:
      moderately_sensitive:
        measure: output/joined/measure_*.csv
  
  generate_lowerGI_symptomcohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_lowerGI_symptom --index-date-range "2018-03-01 to 2023-08-01 by month" --skip-existing --output-dir=output --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_symptom_*.csv.gz
      
  join_lowerGIsymptom:
    run: >
      cohort-joiner:v.0.0.30
        --lhs output/input_symptom_*.csv.gz
        --rhs output/input_demovar.csv.gz
        --output-dir output/joined
        --output-format=csv.gz
    needs: [generate_lowerGI_symptomcohort, generate_demovar_cohort]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_symptomjoined_*.csv.gz

  generate_measures_lowerGIsymptom:
    run: cohortextractor:latest generate_measures --study-definition study_definition_lowerGI_symptom --skip-existing --output-dir=output/joined
    needs: [join_lowerGIsymptom]
    outputs:
      moderately_sensitive:
        measure: output/joined/measure_symptom_*.csv