# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:

  population_size: 10000

version: '3.0'

actions:

  generate_dataset_table:
    run: ehrql:v1 generate-dataset analysis/define_static_dataset.py 
      --output output/data/dataset_static.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_static.csv.gz  

  measures_demo:
    run: ehrql:v1 generate-measures analysis/measures_demo.py
      --output output/measures/measures_demo.csv
      --
      --start-date "2018-03-23"
      --intervals 67
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_demo.csv