version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_basereferral_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_basereferral
    outputs:
      highly_sensitive:
        cohort: output/input_basereferral.csv

  describe:
    run: python:latest python analysis/report_basereferral.py
    needs: [generate_basereferral_cohort]
    outputs:
      moderately_sensitive:
        all_figure: output/colorectal_cancer_7.jpg
        all_figure2: output/colorectal_cancer_8.jpg
        all_figure5: output/colorectal_cancer_9.jpg